<?php
return [
    'VCB' => 'Vietcombank',
    'TCB' => 'Techcombank',
    'ACB' => 'ACB',
    'MB' => 'MB Bank',
    'BIDV' => 'BIDV',
    'VPB' => 'VPBank',
    'VIB' => 'VIB',
    'HDB' => 'HDBank',
    'TPB' => 'TPBank',
    'SHB' => 'SHB',
    'SCB' => 'SCB',
    'EIB' => 'Eximbank',
    'OCB' => 'OCB',
    'MSB' => 'MSB',
    'BAOVIET' => 'Bảo Việt Bank',
    'NAMABANK' => 'Nam Á Bank',
    'LPB' => 'LienVietPostBank',
    'KLB' => 'KienLongBank',
    'ABB' => 'ABBank',
    'VAB' => 'VietABank',
    'SEA' => 'SeaBank',
    'VRB' => 'VRB',
    'NONGHYUP' => 'Nonghyup Bank',
    'WOORI' => 'Woori Bank',
    'IBK' => 'IBK Bank',
];
