<?php

return [
    'VCB' => ['name' => 'Vietcombank', 'logo' => 'https://api.vietqr.io/img/VCB.png'],
    'ACB' => ['name' => 'ACB', 'logo' => 'https://api.vietqr.io/img/ACB.png'],
    'TCB' => ['name' => 'Techcombank', 'logo' => 'https://api.vietqr.io/img/TCB.png'],
    'BIDV' => ['name' => 'BIDV', 'logo' => 'https://api.vietqr.io/img/BIDV.png'],
    'MB' => ['name' => 'MB Bank', 'logo' => 'https://api.vietqr.io/img/MB.png'],
    'VPB' => ['name' => 'VPBank', 'logo' => 'https://api.vietqr.io/img/VPB.png'],
    'VIB' => ['name' => 'VIB', 'logo' => 'https://api.vietqr.io/img/VIB.png'],
    'HDB' => ['name' => 'HDBank', 'logo' => 'https://api.vietqr.io/img/HDB.png'],
    'TPB' => ['name' => 'TPBank', 'logo' => 'https://api.vietqr.io/img/TPB.png'],
    'EIB' => ['name' => 'Eximbank', 'logo' => 'https://api.vietqr.io/img/EIB.png'],
    'STB' => ['name' => 'Sacombank', 'logo' => 'https://api.vietqr.io/img/STB.png'],
    'SCB' => ['name' => 'SCB', 'logo' => 'https://api.vietqr.io/img/SCB.png'],
    'SHB' => ['name' => 'SHB', 'logo' => 'https://api.vietqr.io/img/SHB.png'],
    'MSB' => ['name' => 'MSB', 'logo' => 'https://api.vietqr.io/img/MSB.png'],
    'OCB' => ['name' => 'OCB', 'logo' => 'https://api.vietqr.io/img/OCB.png'],
    'IVB' => ['name' => 'Indovina Bank', 'logo' => 'https://api.vietqr.io/img/IVB.png'],
    'ABB' => ['name' => 'ABBANK', 'logo' => 'https://api.vietqr.io/img/ABB.png'],
    // 'BAOVIET' => ['name' => 'Bảo Việt Bank', 'logo' => 'https://api.vietqr.io/img/BAOVIET.png'],
    'CIMB' => ['name' => 'CIMB Bank', 'logo' => 'https://api.vietqr.io/img/CIMB.png'],
    'PGB' => ['name' => 'PG Bank', 'logo' => 'https://api.vietqr.io/img/PGB.png'],
    'VAB' => ['name' => 'VietABank', 'logo' => 'https://api.vietqr.io/img/VAB.png'],
    'NAB' => ['name' => 'Nam A Bank', 'logo' => 'https://api.vietqr.io/img/NAB.png'],
    'LPB' => ['name' => 'LienVietPostBank', 'logo' => 'https://api.vietqr.io/img/LPB.png'],
    'KLB' => ['name' => 'KienlongBank', 'logo' => 'https://api.vietqr.io/img/KLB.png'],
    // 'BVB' => ['name' => 'Bảo Việt Bank', 'logo' => 'https://api.vietqr.io/img/BVB.png'],
    'SEAB' => ['name' => 'SeABank', 'logo' => 'https://api.vietqr.io/img/SEAB.png'],
    // 'PVCOM' => ['name' => 'PVcomBank', 'logo' => 'https://api.vietqr.io/img/PVCOM.png'],
    'VRB' => ['name' => 'VRB', 'logo' => 'https://api.vietqr.io/img/VRB.png'],
    // 'WOORI' => ['name' => 'Woori Bank', 'logo' => 'https://api.vietqr.io/img/WOORI.png'],
    'HSBC' => ['name' => 'HSBC Vietnam', 'logo' => 'https://api.vietqr.io/img/HSBC.png'],
    'UOB' => ['name' => 'UOB Vietnam', 'logo' => 'https://api.vietqr.io/img/UOB.png'],
    // 'PUBLICBANK' => ['name' => 'Public Bank', 'logo' => 'https://api.vietqr.io/img/PUB.png'],


    // 'AGB' => ['name' => 'Agribank', 'logo' => 'https://api.vietqr.io/img/AGB.png'],
    // 'VTB' => ['name' => 'VietinBank', 'logo' => 'https://api.vietqr.io/img/VTB.png'],
    'GPB' => ['name' => 'GPBank', 'logo' => 'https://api.vietqr.io/img/GPB.png'],
    // 'OJB' => ['name' => 'OceanBank', 'logo' => 'https://api.vietqr.io/img/OJB.png'],
    // 'SGB' => ['name' => 'Saigonbank', 'logo' => 'https://api.vietqr.io/img/SGB.png'],
    'NCB' => ['name' => 'NCB', 'logo' => 'https://api.vietqr.io/img/NCB.png'],
    // 'BACA' => ['name' => 'Bac A Bank', 'logo' => 'https://api.vietqr.io/img/BACA.png'],
    // 'VID' => ['name' => 'VID Public Bank', 'logo' => 'https://api.vietqr.io/img/VID.png'],
    'VCCB' => ['name' => 'Viet Capital Bank', 'logo' => 'https://api.vietqr.io/img/VCCB.png'],
    // 'FRB' => ['name' => 'CBBank (Formerly GPBank)', 'logo' => 'https://api.vietqr.io/img/FRB.png'],

];
